env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions: 
  project : ./tsconfig.json
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
rules: {
  "import/extensions": "off",
  "import/no-unresolved": "off",
  "@typescript-eslint/no-non-null-assertion": "off'
}
